export const VIEW_USERS = {
  LOAD: "LOAD_USERS",
  LOAD_SUCCESS: "LOAD_USERS_SUCCESS",
  LOAD_FAIL: "LOAD_USERS_FAILED",
};

export const CREATE_USERS = "CREATE_USERS";
export const UPDATE_USERS = "UPDATE_USERS";
